export const borderPokemonTypeColors: { [key: string]: string } = {
    normal: "border-gray-600",
    fire: "border-red-700",
    water: "border-blue-600",
    electric: "border-yellow-600",
    grass: "border-green-700",
    ice: "border-cyan-400",
    fighting: "border-red-900",
    poison: "border-purple-800",
    ground: "border-yellow-800",
    flying: "border-indigo-500",
    psychic: "border-pink-700",
    bug: "border-green-900",
    rock: "border-stone-800",
    ghost: "border-purple-900",
    dragon: "border-indigo-900",
    dark: "border-gray-900",
    steel: "border-gray-700",
    fairy: "border-pink-500",
};
