export const pokemonTypeColors: { [key: string]: string } = {
    normal: "bg-gray-400",
    fire: "bg-red-500",
    water: "bg-blue-400",
    electric: "bg-yellow-400",
    grass: "bg-green-500",
    ice: "bg-cyan-200",
    fighting: "bg-red-700",
    poison: "bg-purple-600",
    ground: "bg-yellow-600",
    flying: "bg-indigo-300",
    psychic: "bg-pink-500",
    bug: "bg-green-700",
    rock: "bg-stone-600",
    ghost: "bg-purple-800",
    dragon: "bg-indigo-800",
    dark: "bg-gray-800",
    steel: "bg-gray-500",
    fairy: "bg-pink-300",
};